"use client";

// ============================================================================
// ExecutionBriefView.js — Screen 3 / step-4 handoff renderer
// ============================================================================
//
// PURE RENDERER. Draws whatever brief sections are present and never fetches —
// page.js owns the SSE consumer (streamExecutionBrief) and the brief state, and
// passes it in. Mirrors the MetricProseDetail split-of-concern: the engine lives
// elsewhere; this file only paints.
//
// The six fixed-order blocks (schema canonical in prompt-execution-brief Block 5):
//   bet · prove_next · order · wont_count · gates · handoff
//
// VOICE CONTRACT (a real design rule, not decoration):
//   bet + handoff   -> SERIF (var(--font-serif)), italic — IdeaLoop speaking.
//   prove_next / order / wont_count / gates -> sans / mono — structural.
// If it all renders one font the "product speaks -> hands you structure ->
// speaks again" rhythm is lost.
//
// PROGRESSIVE: each block renders the moment its section lands in `sections`.
//   status "streaming" + block absent -> skeleton; once present -> content.
//
// NULL-NOT-ABSENT (the bug to avoid):
//   resource_clause / close_call_clause / revise_if / stop_if arrive as bare
//   null on the common path. Every conditional is gated `if (has(field))`. A
//   null clause renders NOTHING — never an empty bordered box or a stray label.
//   When BOTH gates fields are null the ENTIRE Decision Gates section renders
//   nothing (not an empty card).
//
// Props:
//   t, analysis            — theme + the settled analysis (for MB context chip)
//   sections               — { bet?, prove_next?, order?, wont_count?, gates?, handoff? }
//   status                 — "idle" | "streaming" | "complete" | "error"
//   error                  — message string when status === "error"
//   retrying               — soft transient-retry notice (boolean)
//   viewingFromSaved, isBranchIdea, profile, user, authLoading
//   getStepNumber          — () => current step (4 for the brief)
//   setCurrentScreen, goToMyIdeas, handleLogout
//   onRegenerate           — () => regenerate the brief (explicit, deliberate)
//   headerStyle, footerStyle
// ============================================================================

import React, { useState, useEffect, useRef } from "react";
import {
  Card,
  PageContainer,
  StepProgress,
  MainBottleneckIcon,
  getMainBottleneckColor,
} from "./components";

const SERIF = "var(--font-serif), Georgia, 'Times New Roman', serif";
const MONO = "ui-monospace, 'SF Mono', Menlo, monospace";

// The founder's closing line is DETERMINISTIC UI COPY the founder writes — never
// generated by the model. Edit this single string to fill the slot; leave it ""
// to show the empty slot affordance.
const FOUNDER_LINE = "";

// ---- guards ----------------------------------------------------------------
const has = (v) => typeof v === "string" && v.trim().length > 0;
const list = (v) => (Array.isArray(v) ? v.filter((x) => has(x)) : []);

// ============================================================ perception layer
// The brief is the subscriber/dark workflow surface. Three brightness tiers do
// the hierarchy: anchor (t.text) -> value (VAL) -> label (t.mut/section colour).
// The transition idea -> execution is carried by the frame: a per-section left
// territory edge (green -> blue -> purple -> red -> amber -> purple), a small
// idea->execution map up top, and a handoff card whose bottom edge is left open.
// Label<->value connection is structural (a bracketed left rule), never a glyph.

// first-letter capitalisation for model fragments ("whether..." -> "Whether...").
// deterministic, idempotent, display-only.
const cap = (s) => (typeof s === "string" && s.length ? s.charAt(0).toUpperCase() + s.slice(1) : s);

// per-section territory palette (dark surface)
const PAL = {
  idea:  { edge: "#1D9E75", icon: "#34d399", chipBg: "rgba(29,158,117,0.13)",  chipBorder: "rgba(29,158,117,0.22)",  wash: "rgba(29,158,117,0.05)", label: "#5e9e83" },
  prove: { edge: "#378ADD", icon: "#60a5fa", chipBg: "rgba(96,165,250,0.13)",  chipBorder: "rgba(96,165,250,0.22)",  inset: "rgba(96,165,250,0.4)", insetBg: "rgba(96,165,250,0.05)" },
  order: { edge: "#7F77DD", icon: "#a78bfa", chipBg: "rgba(139,92,246,0.13)",  chipBorder: "rgba(139,92,246,0.22)",  numBg: "rgba(139,92,246,0.14)", numBorder: "rgba(139,92,246,0.3)" },
  wont:  { edge: "#E24B4A", icon: "#f87171", chipBg: "rgba(248,113,113,0.12)", chipBorder: "rgba(248,113,113,0.22)" },
  gates: { edge: "#e0a93f", icon: "#e0a93f", chipBg: "rgba(234,179,8,0.12)",   chipBorder: "rgba(234,179,8,0.22)" },
  exec:  { edge: "#7F77DD", icon: "#7F77DD", wash: "rgba(127,119,221,0.06)",   dash: "rgba(127,119,221,0.45)", ring: "rgba(127,119,221,0.7)", label: "#9a93e0" },
};
const PRODUCES = { rule: "#6fa890", label: "#7bb6a3" };
const SIGNAL   = { rule: "#6e93c4", label: "#7ba0c9" };
const REVISE   = { rule: "#e0a93f", label: "#e0a93f" };
const STOP     = { rule: "#f08a8a", label: "#f08a8a" };
const VAL  = "#b4b9c2"; // supporting value
const VAL2 = "#c8ccd4"; // won't-count / gates value (a touch brighter)

// inline Tabler outline paths (the app has no icon font; mirrors the crossing).
const ICONS = {
  flask:  ["M6.1 15h11.8", "M14 3v7.342a6 6 0 0 1 1.318 10.658h-6.635a6 6 0 0 1 1.317 -10.66v-7.34h4", "M9 3h6"],
  route:  ["M3 19a2 2 0 1 0 4 0a2 2 0 0 0 -4 0", "M19 7a2 2 0 1 0 0 -4a2 2 0 0 0 0 4", "M11 19h5.5a3.5 3.5 0 0 0 0 -7h-8a3.5 3.5 0 0 1 0 -7h4.5"],
  ban:    ["M3 12a9 9 0 1 0 18 0a9 9 0 1 0 -18 0", "M5.7 5.7l12.6 12.6"],
  split:  ["M21 17h-8l-3.5 -5h-6.5", "M21 7h-8l-3.495 5", "M18 10l3 -3l-3 -3", "M18 20l3 -3l-3 -3"],
  brain:  ["M15.5 13a3.5 3.5 0 0 0 -3.5 3.5v1a3.5 3.5 0 0 0 7 0v-1.8", "M8.5 13a3.5 3.5 0 0 1 3.5 3.5v1a3.5 3.5 0 0 1 -7 0v-1.8", "M17.5 16a3.5 3.5 0 0 0 0 -7h-.5", "M19 9.3v-2.8a3.5 3.5 0 0 0 -7 0", "M6.5 16a3.5 3.5 0 0 1 0 -7h.5", "M5 9.3v-2.8a3.5 3.5 0 0 1 7 0v10"],
  laptop: ["M3 19l18 0", "M5 7a1 1 0 0 1 1 -1h12a1 1 0 0 1 1 1v8a1 1 0 0 1 -1 1h-12a1 1 0 0 1 -1 -1l0 -8"],
  x:      ["M18 6l-12 12", "M6 6l12 12"],
};
function BriefIcon({ name, size = 16, color = "currentColor", stroke = 2 }) {
  const paths = ICONS[name] || [];
  return (
    <svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke={color} strokeWidth={stroke}
         strokeLinecap="round" strokeLinejoin="round" aria-hidden="true" style={{ flexShrink: 0, display: "block" }}>
      {paths.map((d, i) => <path key={i} d={d} />)}
    </svg>
  );
}

// streaming placeholder
function Skeleton({ t, lines = 2 }) {
  return (
    <div style={{ display: "flex", flexDirection: "column", gap: 9 }} aria-hidden="true">
      {Array.from({ length: lines }).map((_, i) => (
        <div key={i} style={{ height: 11, width: i === lines - 1 ? "62%" : "100%", borderRadius: 6, background: t.barBg, opacity: 0.7 }} />
      ))}
    </div>
  );
}
// render content when present; skeleton while streaming; else nothing
const gate = (data, status, render, t, skeletonLines = 3) => {
  if (data) return render();
  if (status === "streaming") return <Skeleton t={t} lines={skeletonLines} />;
  return null;
};

// the per-block territory card: a 3px coloured left edge + the body. bet/handoff
// pass `wash` + bordered=false (open, tinted); handoff also dashedBottom (open door).
function TerritoryCard({ edge, wash, bordered = true, dashedBottom = false, t, children }) {
  return (
    <div style={{ display: "flex", borderRadius: 14, overflow: "hidden", border: bordered ? `1px solid ${t.border}` : "none", marginBottom: 12 }}>
      <div style={{ width: 3, background: edge, flexShrink: 0 }} />
      <div style={{
        flex: 1, minWidth: 0,
        background: wash || t.surface,
        padding: "20px 22px",
        borderBottom: dashedBottom ? `1.5px dashed ${PAL.exec.dash}` : "none",
        borderRadius: dashedBottom ? "0 0 8px 8px" : 0,
      }}>
        {children}
      </div>
    </div>
  );
}

function SectionHead({ icon, color, chipBg, chipBorder, q, t }) {
  return (
    <div style={{ display: "flex", alignItems: "center", gap: 11, marginBottom: 15 }}>
      <div style={{ width: 30, height: 30, borderRadius: 8, display: "flex", alignItems: "center", justifyContent: "center", background: chipBg, border: `1px solid ${chipBorder}` }}>
        <BriefIcon name={icon} size={16} color={color} />
      </div>
      <p style={{ fontSize: 15, fontWeight: 600, color: t.text, margin: 0 }}>{q}</p>
    </div>
  );
}

// Option-2 connector: label + value share a coloured left rule -> one bracketed
// unit. The rule's colour carries the meaning; no glyph.
function Bracket({ rule, labelColor, label, mt = 0, children }) {
  return (
    <div style={{ borderLeft: `1.5px solid ${rule}`, paddingLeft: 13, marginTop: mt }}>
      <p style={{ fontSize: 10.5, letterSpacing: "0.1em", textTransform: "uppercase", color: labelColor, fontWeight: 700, margin: "0 0 3px" }}>{label}</p>
      {children}
    </div>
  );
}

// in-step modifier callouts. resource -> amber (a constraint); close_call ->
// indigo (a judgement). RENDERED ONLY when text is present (null path draws nothing).
function ClauseBox({ kind, text, t }) {
  const isRes = kind === "resource";
  const accent = isRes ? "rgba(234,179,8,0.38)" : "rgba(127,119,221,0.35)";
  const lead   = isRes ? "#c79a3a" : "#9a93e0";
  const label  = isRes ? "Resource clause" : "Close call";
  const bg     = isRes ? "rgba(234,179,8,0.05)" : "rgba(127,119,221,0.05)";
  return (
    <div style={{ background: bg, borderLeft: `2px solid ${accent}`, borderRadius: "0 8px 8px 0", padding: "9px 13px", marginTop: 9 }}>
      <p style={{ fontSize: 13, lineHeight: 1.5, color: VAL, margin: 0 }}>
        <span style={{ color: lead, fontWeight: 600 }}>{label} — </span>{cap(text)}
      </p>
    </div>
  );
}

function XItem({ text, last }) {
  return (
    <div style={{ display: "flex", alignItems: "flex-start", gap: 10, marginBottom: last ? 0 : 10 }}>
      <span style={{ flexShrink: 0, marginTop: 2 }}><BriefIcon name="x" size={14} color="#f87171" stroke={2.2} /></span>
      <span style={{ fontSize: 14, lineHeight: 1.5, color: VAL2 }}>{cap(text)}</span>
    </div>
  );
}

// Sticky reading-crossing: pins under the (non-sticky) header as you scroll and
// fills like the SSE pulse — each station lights in its colour as you pass it, the
// line completes and the execution ring solidifies when you reach the founder note.
// Driven by `prog` (0..1) computed in the parent from scroll position. The pulse
// breathes unless prefers-reduced-motion.
const MAP_DOTS = [
  { p: 9,  c: "#34d399" },
  { p: 25, c: "#60a5fa" },
  { p: 42, c: "#a78bfa" },
  { p: 59, c: "#f87171" },
  { p: 75, c: "#e0a93f" },
  { p: 91, c: "#a78bfa" },
];
function StickyCrossing({ prog, reduce, barRef, t }) {
  const pct = Math.max(0, Math.min(1, prog || 0)) * 100;
  const done = (prog || 0) >= 0.985;
  return (
    <div ref={barRef} style={{ position: "sticky", top: 0, zIndex: 20, background: t.bg, padding: "12px 0 11px", marginBottom: 18, borderBottom: `1px solid ${t.divider}` }}>
      <style>{`@keyframes ebBreathe{0%,100%{transform:translate(-50%,-50%) scale(1);opacity:.7}50%{transform:translate(-50%,-50%) scale(1.22);opacity:1}}`}</style>
      <div style={{ position: "relative", height: 28 }}>
        <div style={{ position: "absolute", left: 28, right: 30, top: 0, bottom: 0 }}>
          <div style={{ position: "absolute", left: 0, right: 0, top: "50%", height: 2, transform: "translateY(-50%)", background: t.divider }} />
          <div style={{ position: "absolute", left: 0, width: `${pct}%`, top: "50%", height: 2, transform: "translateY(-50%)", background: "#7F77DD" }} />
          {MAP_DOTS.map((d, i) => {
            const lit = pct >= d.p - 1;
            return (
              <span key={i} style={{ position: "absolute", left: `${d.p}%`, top: "50%", width: 9, height: 9, borderRadius: "50%", background: lit ? d.c : t.surfAlt, border: lit ? "none" : `1px solid ${t.border}`, opacity: lit ? 1 : 0.7, transform: `translate(-50%,-50%) scale(${lit ? 1.15 : 1})`, transition: "all .2s" }} />
            );
          })}
          <span style={{ position: "absolute", left: `${pct}%`, top: "50%", width: 11, height: 11, borderRadius: "50%", background: "#7F77DD", transform: "translate(-50%,-50%)", opacity: done ? 0 : 1, boxShadow: "0 0 0 4px rgba(127,119,221,0.16)", transition: "opacity .2s", animation: reduce ? "none" : "ebBreathe 1.5s ease-in-out infinite" }} />
        </div>
        <div style={{ position: "absolute", left: 14, top: "50%", transform: "translate(-50%,-50%)", width: 28, height: 28, borderRadius: "50%", background: PAL.idea.chipBg, border: `1px solid ${PAL.idea.edge}`, display: "flex", alignItems: "center", justifyContent: "center" }}>
          <BriefIcon name="brain" size={15} color={PAL.idea.icon} />
        </div>
        <div style={{ position: "absolute", right: 14, top: "50%", transform: `translate(50%,-50%) scale(${done ? 1.12 : 1})`, width: 28, height: 28, borderRadius: "50%", background: "transparent", border: `1.5px dashed ${done ? "#7F77DD" : PAL.exec.ring}`, display: "flex", alignItems: "center", justifyContent: "center", transition: "all .25s" }}>
          <BriefIcon name="laptop" size={15} color={PAL.exec.icon} />
        </div>
      </div>
      <p style={{ fontSize: 11.5, color: t.mut, margin: "7px 0 0", paddingLeft: 40 }}>
        {done ? "Over to you \u2014 it\u2019s yours now." : "From your idea, across the evidence, toward execution."}
      </p>
    </div>
  );
}

// ================================================================ block bodies
function BetBlock({ sections, status, t }) {
  if (!sections.bet && status !== "streaming") return null;
  return (
    <TerritoryCard edge={PAL.idea.edge} wash={PAL.idea.wash} bordered={false} t={t}>
      <p style={{ fontSize: 11, letterSpacing: "0.15em", textTransform: "uppercase", color: PAL.idea.label, fontWeight: 700, margin: "0 0 8px" }}>Idea · the bet</p>
      {gate(sections.bet, status,
        () => (has(sections.bet.text)
          ? <p style={{ fontFamily: SERIF, fontStyle: "italic", fontSize: 16.5, lineHeight: 1.58, color: t.text, margin: 0 }}>{cap(sections.bet.text)}</p>
          : null),
        t, 2)}
    </TerritoryCard>
  );
}

function ProveNextBlock({ sections, status, t }) {
  return (
    <TerritoryCard edge={PAL.prove.edge} t={t}>
      <SectionHead icon="flask" color={PAL.prove.icon} chipBg={PAL.prove.chipBg} chipBorder={PAL.prove.chipBorder} q="What you have to prove next" t={t} />
      {gate(sections.prove_next, status, () => {
        const { evidence, bar } = sections.prove_next;
        return (
          <>
            {has(evidence) && (
              <p style={{ fontSize: 14.5, lineHeight: 1.62, color: t.text, fontWeight: 500, margin: has(bar) ? "0 0 12px" : 0 }}>{cap(evidence)}</p>
            )}
            {has(bar) && (
              <div style={{ background: PAL.prove.insetBg, borderLeft: `2px solid ${PAL.prove.inset}`, borderRadius: "0 8px 8px 0", padding: "10px 14px" }}>
                <p style={{ fontSize: 11, letterSpacing: "0.06em", textTransform: "uppercase", color: t.mut, fontWeight: 700, margin: "0 0 3px" }}>What counts as enough</p>
                <p style={{ fontSize: 13.5, lineHeight: 1.55, color: VAL, margin: 0 }}>{cap(bar)}</p>
              </div>
            )}
          </>
        );
      }, t, 3)}
    </TerritoryCard>
  );
}

function OrderBlock({ sections, status, t }) {
  return (
    <TerritoryCard edge={PAL.order.edge} t={t}>
      <SectionHead icon="route" color={PAL.order.icon} chipBg={PAL.order.chipBg} chipBorder={PAL.order.chipBorder} q="The order this forces" t={t} />
      {gate(sections.order, status, () => {
        const steps = Array.isArray(sections.order.steps) ? sections.order.steps : [];
        if (steps.length === 0) return null;
        return (
          <div style={{ display: "flex", flexDirection: "column", gap: 20 }}>
            {steps.map((step, i) => (
              <div key={step?.n ?? i} style={{ display: "flex", gap: 13 }}>
                <span style={{ width: 24, height: 24, borderRadius: "50%", flexShrink: 0, display: "flex", alignItems: "center", justifyContent: "center", fontFamily: MONO, fontSize: 12, fontWeight: 600, background: PAL.order.numBg, border: `1px solid ${PAL.order.numBorder}`, color: PAL.order.icon }}>
                  {step?.n ?? i + 1}
                </span>
                <div style={{ flex: 1, minWidth: 0 }}>
                  {has(step?.action) && (
                    <p style={{ fontSize: 14.5, lineHeight: 1.6, color: t.text, fontWeight: 500, margin: 0 }}>{cap(step.action)}</p>
                  )}
                  {has(step?.produces) && (
                    <Bracket rule={PRODUCES.rule} labelColor={PRODUCES.label} label="Produces" mt={13}>
                      <p style={{ fontSize: 13.5, lineHeight: 1.55, color: VAL, margin: 0 }}>{cap(step.produces)}</p>
                    </Bracket>
                  )}
                  {has(step?.signal) && (
                    <Bracket rule={SIGNAL.rule} labelColor={SIGNAL.label} label="Signal" mt={11}>
                      <p style={{ fontSize: 13.5, lineHeight: 1.55, color: VAL, margin: 0 }}>{cap(step.signal)}</p>
                    </Bracket>
                  )}
                  {has(step?.resource_clause) && <ClauseBox kind="resource" text={step.resource_clause} t={t} />}
                  {has(step?.close_call_clause) && <ClauseBox kind="close_call" text={step.close_call_clause} t={t} />}
                </div>
              </div>
            ))}
          </div>
        );
      }, t, 4)}
    </TerritoryCard>
  );
}

function WontCountBlock({ sections, status, t }) {
  return (
    <TerritoryCard edge={PAL.wont.edge} t={t}>
      <SectionHead icon="ban" color={PAL.wont.icon} chipBg={PAL.wont.chipBg} chipBorder={PAL.wont.chipBorder} q="What won't count" t={t} />
      {gate(sections.wont_count, status, () => {
        const moves = list(sections.wont_count.moves);
        const signals = list(sections.wont_count.signals);
        return (
          <>
            {moves.length > 0 && (
              <div style={{ marginBottom: signals.length > 0 ? 16 : 0 }}>
                <p style={{ fontSize: 11.5, color: t.mut, fontWeight: 600, margin: "0 0 11px" }}>Moves that feel like progress but don&apos;t move the evidence</p>
                {moves.map((m, i) => <XItem key={i} text={m} last={i === moves.length - 1} />)}
              </div>
            )}
            {signals.length > 0 && (
              <div>
                <p style={{ fontSize: 11.5, color: t.mut, fontWeight: 600, margin: "0 0 11px" }}>Signals that look like proof but aren&apos;t</p>
                {signals.map((s, i) => <XItem key={i} text={s} last={i === signals.length - 1} />)}
              </div>
            )}
          </>
        );
      }, t, 4)}
    </TerritoryCard>
  );
}

// Decision gates — stop-loss only. Renders NOTHING when both fields are null
// (honest empty), and no skeleton (gates may legitimately never arrive).
function GatesBlock({ sections, status, t }) {
  const d = sections.gates;
  if (!d) return null;
  const reviseIf = d.revise_if;
  const stopIf = d.stop_if;
  if (!has(reviseIf) && !has(stopIf)) return null;
  return (
    <TerritoryCard edge={PAL.gates.edge} t={t}>
      <SectionHead icon="split" color={PAL.gates.icon} chipBg={PAL.gates.chipBg} chipBorder={PAL.gates.chipBorder} q="Decision gates" t={t} />
      {has(reviseIf) && (
        <Bracket rule={REVISE.rule} labelColor={REVISE.label} label="Revise if">
          <p style={{ fontSize: 14, lineHeight: 1.55, color: VAL2, margin: 0 }}>{cap(reviseIf)}</p>
        </Bracket>
      )}
      {has(stopIf) && (
        <div style={{ marginTop: has(reviseIf) ? 13 : 0 }}>
          <Bracket rule={STOP.rule} labelColor={STOP.label} label="Stop if">
            <p style={{ fontSize: 14, lineHeight: 1.55, color: VAL2, margin: 0 }}>{cap(stopIf)}</p>
          </Bracket>
        </div>
      )}
    </TerritoryCard>
  );
}

function HandoffBlock({ sections, status, t }) {
  if (!sections.handoff && status !== "streaming") return null;
  return (
    <TerritoryCard edge={PAL.exec.edge} wash={PAL.exec.wash} bordered={false} dashedBottom t={t}>
      <p style={{ fontSize: 11, letterSpacing: "0.15em", textTransform: "uppercase", color: PAL.exec.label, fontWeight: 700, margin: "0 0 8px" }}>Execution · yours now</p>
      {gate(sections.handoff, status,
        () => (has(sections.handoff.text)
          ? <p style={{ fontFamily: SERIF, fontStyle: "italic", fontSize: 16.5, lineHeight: 1.58, color: t.text, margin: 0 }}>{cap(sections.handoff.text)}</p>
          : null),
        t, 2)}
    </TerritoryCard>
  );
}

// Terminal action row — the brief is the end of the flow, so it must never be a
// dead end. The brief has NO independent save: it persists WITH the idea through
// the canonical results2 save flow (the normal-save body carries briefData). So:
//   - fresh, normal idea (not saved, not a re-eval), brief complete -> a primary
//     "Save this idea" that pre-opens results2's normal naming form (onSaveIdea).
//     Once saved (saveStatus "saved") -> swap to "View in My Ideas".
//   - saved idea (viewingFromSaved): the brief is already persisted (generated
//     from the hub straight onto the row) -> no save, just escape hatches.
//   - re-eval result: saving is the BRANCH flow on results2 (and a branch
//     persists its brief via generate-from-hub, not this body) -> no save claim
//     here; route back to analysis where the branch decision block lives.
// Look-freely-save-optionally: never pressure a save or imply the brief is lost
// without one — going back and saving carries it along.
function BriefFooterActions({
  t, status, viewingFromSaved, isReEvalResult, saveStatus,
  onSaveIdea, onNewIdea, goToMyIdeas, setCurrentScreen, onRegenerate,
}) {
  const linkBtn = {
    fontSize: 13, color: t.sec, background: "none",
    border: `1px solid ${t.border}`, borderRadius: 9999,
    padding: "9px 18px", cursor: "pointer",
  };
  const primaryBtn = {
    fontSize: 14, fontWeight: 600, color: t.ctaText, background: t.ctaBg,
    border: "none", borderRadius: 12, padding: "13px 26px", cursor: "pointer",
  };

  // Save affordance only on the fresh, normal-save path with a complete brief.
  const canSaveHere =
    !viewingFromSaved && !isReEvalResult && status === "complete";
  const alreadySaved = saveStatus === "saved";

  return (
    <div style={{ borderTop: `1px solid ${t.divider}`, paddingTop: 22, marginBottom: 22 }}>
      {canSaveHere && !alreadySaved && (
        <div style={{ marginBottom: 14 }}>
          <button onClick={() => onSaveIdea && onSaveIdea()} style={{ ...primaryBtn, width: "100%" }}>
            Save this idea →
          </button>
          <p style={{ fontSize: 12, color: t.mut, textAlign: "center", margin: "8px 0 0", lineHeight: 1.5 }}>
            Saving keeps this idea and its brief together. You can read it without saving.
          </p>
        </div>
      )}

      {canSaveHere && alreadySaved && (
        <div style={{ marginBottom: 14, display: "flex", alignItems: "center", justifyContent: "center", gap: 10 }}>
          <span style={{ fontSize: 13, fontWeight: 600, color: t.stepDone }}>✓ Saved — brief attached</span>
        </div>
      )}

      <div style={{ display: "flex", gap: 10, justifyContent: "center", flexWrap: "wrap" }}>
        <button onClick={() => setCurrentScreen("results2")} style={linkBtn}>← Back to analysis</button>
        <button onClick={() => goToMyIdeas && goToMyIdeas()} style={linkBtn}>My Ideas</button>
        {onNewIdea && (
          <button onClick={() => onNewIdea()} style={linkBtn}>Start a new idea</button>
        )}
        {status === "complete" && onRegenerate && (
          <button
            onClick={() => onRegenerate()}
            style={{ ...linkBtn, color: t.mut, border: `1px solid ${t.border}` }}
          >
            Regenerate brief
          </button>
        )}
      </div>
    </div>
  );
}

function FounderSlot({ t }) {
  return (
    <div style={{ borderTop: `1px solid ${t.divider}`, paddingTop: 22, marginBottom: 22 }}>
      <div style={{ display: "flex", alignItems: "center", gap: 7, marginBottom: 9 }}>
        <span style={{ fontSize: 13 }}>🚩</span>
        <span style={{ fontSize: 12, color: t.sec, letterSpacing: "0.03em" }}>Founder to a founder</span>
      </div>
      {has(FOUNDER_LINE) ? (
        <p style={{ fontFamily: SERIF, fontStyle: "italic", fontSize: 15, lineHeight: 1.6, color: t.sec, margin: 0 }}>
          {FOUNDER_LINE}
        </p>
      ) : (
        <div
          style={{
            border: `1px dashed ${t.border}`,
            borderRadius: 10,
            padding: "14px 16px",
            display: "flex",
            alignItems: "center",
            justifyContent: "center",
            background: t.surfAlt,
          }}
        >
          <span style={{ fontSize: 13, color: t.mut, fontStyle: "italic" }}>— your line goes here —</span>
        </div>
      )}
    </div>
  );
}

// The loading "crossing" — the brief's streaming surface. NOT "thinking" (that's
// idea-territory, analyze's console). This is the handoff: a pulse crossing from
// the evaluated idea, across the six brief sections (our evidence-based structure),
// to the threshold of execution — which stays an open, dashed, UNCLAIMED ring.
// We carry the work to the edge and stop; how they execute is the dashed space we
// deliberately don't draw. Paced by a gentle timer but gated by completion: it
// holds on the last step until status flips to "complete", then plays the arrival.
const X_POS = [15, 27, 39, 51, 63, 75];
const X_STAGES = [
  "Reading what you\u2019ve proven",
  "Naming the bet",
  "Setting what you must prove",
  "Sequencing what to prove first",
  "Marking the false signals",
  "Drawing the stop-and-go lines",
  "Writing the handoff",
];
const XPURP = "#7F77DD";
const XDONE = "#1D9E75";

function BriefCrossing({ t, status }) {
  const arrived = status === "complete";
  const [idx, setIdx] = useState(0);
  useEffect(() => {
    if (arrived) return; // stepping stops; arrival beat takes over
    const id = setInterval(() => setIdx((i) => Math.min(i + 1, X_STAGES.length - 1)), 1250);
    return () => clearInterval(id);
  }, [arrived]);

  const node = idx - 1; // -1 during the intro beat
  const travLeft = arrived ? 90 : idx === 0 ? 3 : X_POS[Math.min(node, X_POS.length - 1)];
  const progW = arrived ? 87 : idx === 0 ? 0 : Math.max(0, travLeft - 3);
  const nodeDone = (j) => arrived || j < node;
  const statusText = arrived ? "Over to you \u2014 it\u2019s yours now" : X_STAGES[idx];
  const topText = arrived ? "IdeaLoop Core" : "IdeaLoop Core \u00b7 handing off";

  const epl = {
    position: "absolute", top: 46, transform: "translateX(-50%)",
    fontSize: 11, letterSpacing: "0.04em", textTransform: "uppercase",
    color: t.mut, whiteSpace: "nowrap", display: "flex", alignItems: "center", gap: 5,
  };

  return (
    <div style={{ width: "100%", maxWidth: 380, display: "flex", flexDirection: "column", alignItems: "center", gap: 30 }}>
      <span style={{ fontSize: 11, letterSpacing: "0.08em", textTransform: "uppercase", color: t.mut }}>{topText}</span>
      <div style={{ width: "100%", position: "relative", height: 66 }}>
        <div style={{ position: "absolute", top: 24, left: "3%", width: "75%", height: 2, background: t.divider, transform: "translateY(-50%)" }} />
        <div style={{ position: "absolute", top: 24, left: "78%", width: "20%", borderTop: `1.5px dashed ${t.border}`, opacity: 0.45, transform: "translateY(-50%)" }} />
        <div style={{ position: "absolute", top: 24, left: "3%", width: `${progW}%`, height: 2, background: XPURP, transform: "translateY(-50%)", transition: "width .7s cubic-bezier(.4,0,.2,1)" }} />
        <span style={{ position: "absolute", top: 24, left: "3%", width: 13, height: 13, borderRadius: "50%", background: XDONE, transform: "translate(-50%,-50%)" }} />
        <span style={{ position: "absolute", top: 24, left: "90%", width: 16, height: 16, borderRadius: "50%", border: `1.5px dashed ${arrived ? XPURP : t.border}`, background: "transparent", transform: `translate(-50%,-50%) scale(${arrived ? 1.25 : 1})`, transition: "transform .5s, border-color .5s" }} />
        {X_POS.map((p, j) => (
          <span key={j} style={{ position: "absolute", top: 24, left: `${p}%`, width: 9, height: 9, borderRadius: "50%", background: nodeDone(j) ? XDONE : t.surfAlt, border: `1.5px solid ${nodeDone(j) ? XDONE : t.border}`, transform: "translate(-50%,-50%)", transition: "all .3s" }} />
        ))}
        <span style={{ position: "absolute", top: 24, left: `${travLeft}%`, width: 20, height: 20, borderRadius: "50%", background: XPURP, transform: "translate(-50%,-50%)", opacity: arrived ? 0 : 1, transition: "left .7s cubic-bezier(.4,0,.2,1), opacity .4s ease .55s", animation: "ebBreathe 1.5s ease-in-out infinite", boxShadow: "0 0 0 4px rgba(127,119,221,0.14)" }} />
        <span style={{ ...epl, left: "3%" }}>
          <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" style={{ flexShrink: 0 }} aria-hidden="true">
            <path d="M15.5 13a3.5 3.5 0 0 0 -3.5 3.5v1a3.5 3.5 0 0 0 7 0v-1.8" />
            <path d="M8.5 13a3.5 3.5 0 0 1 3.5 3.5v1a3.5 3.5 0 0 1 -7 0v-1.8" />
            <path d="M17.5 16a3.5 3.5 0 0 0 0 -7h-.5" />
            <path d="M19 9.3v-2.8a3.5 3.5 0 0 0 -7 0" />
            <path d="M6.5 16a3.5 3.5 0 0 1 0 -7h.5" />
            <path d="M5 9.3v-2.8a3.5 3.5 0 0 1 7 0v10" />
          </svg>
          idea
        </span>
        <span style={{ ...epl, left: "90%" }}>
          <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" style={{ flexShrink: 0 }} aria-hidden="true">
            <path d="M3 19l18 0" />
            <path d="M5 7a1 1 0 0 1 1 -1h12a1 1 0 0 1 1 1v8a1 1 0 0 1 -1 1h-12a1 1 0 0 1 -1 -1l0 -8" />
          </svg>
          execution
        </span>
      </div>
      <div style={{ fontSize: 14, color: t.text, textAlign: "center", minHeight: 20, transition: "opacity .3s" }}>{statusText}</div>
    </div>
  );
}

// ==================================================================== screen
export default function ExecutionBriefView({
  t,
  analysis,
  sections = {},
  status = "idle",
  error = "",
  retrying = false,
  viewingFromSaved = false,
  isBranchIdea = false,
  isReEvalResult = false,
  saveStatus,
  savedIdeaId,
  profile,
  user,
  authLoading,
  getStepNumber,
  setCurrentScreen,
  goToMyIdeas,
  handleLogout,
  onRegenerate,
  onSaveIdea,
  onNewIdea,
  headerStyle,
  footerStyle,
}) {
  const mb = analysis?.estimates?.main_bottleneck;
  const mbColor = mb && mb !== "Specification" ? getMainBottleneckColor(mb, t.mode) : null;

  const nothingYet = !Object.keys(sections || {}).length;
  const fullError = status === "error" && nothingYet; // failed before any block

  // Crossing overlay lifecycle. Show it only when we actually STREAM (didStream),
  // so a seeded/saved brief that mounts already "complete" never flashes it. On
  // complete, hold ~1.2s for the arrival beat ("over to you"), then fade out and
  // reveal the now-sharp brief behind.
  const didStreamRef = useRef(false);
  const [overlay, setOverlay] = useState("hidden"); // "hidden" | "up" | "fading"
  useEffect(() => {
    if (status === "streaming") {
      didStreamRef.current = true;
      setOverlay("up");
      return;
    }
    if (status === "complete") {
      if (!didStreamRef.current) { setOverlay("hidden"); return; }
      const a = setTimeout(() => setOverlay("fading"), 1200);
      const b = setTimeout(() => { setOverlay("hidden"); didStreamRef.current = false; }, 1650);
      return () => { clearTimeout(a); clearTimeout(b); };
    }
    setOverlay("hidden"); // idle / error
  }, [status]);

  // Sticky-crossing scroll progress: 0 at the top of the brief, 1 when the
  // founder note reaches the pinned bar. Computed from the two sentinels and the
  // bar height; if the brief is too short to scroll, it simply starts complete.
  const barRef = useRef(null);
  const topRef = useRef(null);
  const founderRef = useRef(null);
  const [prog, setProg] = useState(0);
  const reduce =
    typeof window !== "undefined" &&
    window.matchMedia &&
    window.matchMedia("(prefers-reduced-motion: reduce)").matches;

  useEffect(() => {
    let raf = 0;
    const calc = () => {
      raf = 0;
      if (!topRef.current || !founderRef.current) return;
      const sy = window.scrollY || document.documentElement.scrollTop || 0;
      const max = (document.documentElement.scrollHeight || 0) - window.innerHeight;
      const barH = barRef.current ? barRef.current.offsetHeight : 72;
      const startY = topRef.current.getBoundingClientRect().top + sy - barH;
      const endY = founderRef.current.getBoundingClientRect().top + sy - barH;
      let p = endY > startY ? (sy - startY) / (endY - startY) : 1;
      if (max <= 4 || sy >= max - 2) p = 1; // too short to scroll, or bottom reached -> complete
      setProg(Math.max(0, Math.min(1, p)));
    };
    const onScroll = () => { if (!raf) raf = requestAnimationFrame(calc); };
    window.addEventListener("scroll", onScroll, { passive: true });
    window.addEventListener("resize", onScroll);
    calc();
    const t1 = setTimeout(calc, 300);
    const t2 = setTimeout(calc, 1200); // re-measure after late layout / fonts
    return () => {
      window.removeEventListener("scroll", onScroll);
      window.removeEventListener("resize", onScroll);
      cancelAnimationFrame(raf);
      clearTimeout(t1); clearTimeout(t2);
    };
  }, [status, sections]);

  return (
    <div style={{ minHeight: "100vh", background: t.bg, color: t.text, display: "flex", flexDirection: "column", overflowX: "clip" }}>
      <header style={headerStyle}>
        <PageContainer wide>
          <div style={{ padding: "16px 0", display: "flex", justifyContent: "space-between", alignItems: "center" }}>
            <h1
              onClick={() => setCurrentScreen(profile && profile.coding && profile.ai ? "input" : "profile")}
              style={{ fontSize: 14, fontFamily: MONO, letterSpacing: "0.1em", textTransform: "uppercase", color: t.mut, margin: 0, cursor: "pointer" }}
            >
              IdeaLoop Core
            </h1>
            <div style={{ display: "flex", alignItems: "center", gap: 12 }}>
              <button
                onClick={() => setCurrentScreen("results2")}
                style={{ fontSize: 12, color: t.mut, background: "none", border: "none", cursor: "pointer" }}
              >
                ← Back to analysis
              </button>
              {!authLoading && user && (
                <>
                  <span style={{ color: t.divider }}>|</span>
                  {!viewingFromSaved && (
                    <>
                      <button onClick={goToMyIdeas} style={{ fontSize: 12, color: t.link, background: "none", border: "none", cursor: "pointer", fontWeight: 500 }}>
                        My Ideas
                      </button>
                      <span style={{ color: t.divider }}>|</span>
                    </>
                  )}
                  <span style={{ fontSize: 12, color: t.mut }}>{user.email}</span>
                  <button onClick={handleLogout} style={{ fontSize: 12, color: t.mut, background: "none", border: "none", cursor: "pointer" }}>
                    Log out
                  </button>
                </>
              )}
            </div>
          </div>
        </PageContainer>
      </header>

      <StepProgress
        currentStep={getStepNumber ? getStepNumber() : 4}
        savedMode={viewingFromSaved}
        branchMode={viewingFromSaved && isBranchIdea}
        t={t}
      />

      <main style={{ flex: 1, paddingBottom: 64 }}>
        <PageContainer wide>
          {/* title */}
          <div style={{ display: "flex", alignItems: "center", gap: 12, marginBottom: 18 }}>
            <div
              style={{
                width: 42,
                height: 42,
                borderRadius: 11,
                background: "rgba(124,92,252,0.13)",
                border: "1px solid rgba(124,92,252,0.3)",
                display: "flex",
                alignItems: "center",
                justifyContent: "center",
                fontSize: 20,
                flexShrink: 0,
              }}
            >
              ➜
            </div>
            <div>
              <p style={{ fontSize: 19, fontWeight: 600, color: t.text, margin: 0 }}>Execution brief</p>
              <p style={{ fontSize: 13, color: t.mut, margin: "2px 0 0" }}>Where our read stops · your handoff</p>
            </div>
            {mb && mbColor && (
              <span
                style={{
                  marginLeft: "auto",
                  display: "inline-flex",
                  alignItems: "center",
                  gap: 6,
                  fontSize: 12,
                  fontWeight: 600,
                  padding: "5px 12px",
                  borderRadius: 9999,
                  background: mbColor.bg,
                  color: mbColor.color,
                  border: `1px solid ${mbColor.border}`,
                  whiteSpace: "nowrap",
                }}
              >
                <MainBottleneckIcon value={mb} size={13} />
                {mb}
              </span>
            )}
          </div>

          {/* soft transient-retry notice */}
          {retrying && status === "streaming" && (
            <div
              style={{
                fontSize: 13,
                color: t.sec,
                background: t.surfAlt,
                border: `1px solid ${t.border}`,
                borderRadius: 10,
                padding: "10px 14px",
                marginBottom: 16,
              }}
            >
              Hit a brief snag generating this — retrying. Thanks for your patience.
            </div>
          )}

          {/* full-failure state (failed before any block streamed) */}
          {fullError ? (
            <Card style={{ padding: 28, textAlign: "center" }} t={t}>
              <p style={{ fontSize: 14, color: t.sec, lineHeight: 1.6, margin: "0 0 16px" }}>
                {error || "We couldn't generate the execution brief just now."}
              </p>
              {onRegenerate && (
                <button
                  onClick={() => onRegenerate()}
                  style={{
                    background: t.ctaBg,
                    color: t.ctaText,
                    border: "none",
                    borderRadius: 10,
                    padding: "11px 26px",
                    fontSize: 13,
                    fontWeight: 600,
                    cursor: "pointer",
                  }}
                >
                  Try again
                </button>
              )}
            </Card>
          ) : (
            <>
              <StickyCrossing prog={prog} reduce={reduce} barRef={barRef} t={t} />
              <div ref={topRef} aria-hidden="true" style={{ height: 0 }} />
              <BetBlock sections={sections} status={status} t={t} />
              <ProveNextBlock sections={sections} status={status} t={t} />
              <OrderBlock sections={sections} status={status} t={t} />
              <WontCountBlock sections={sections} status={status} t={t} />
              <GatesBlock sections={sections} status={status} t={t} />
              <HandoffBlock sections={sections} status={status} t={t} />

              {/* inline error AFTER some content already streamed */}
              {status === "error" && !nothingYet && (
                <p style={{ fontSize: 13, color: t.riskNum, margin: "0 0 22px", lineHeight: 1.5 }}>
                  {error || "The brief stopped before finishing."}
                  {onRegenerate && (
                    <button
                      onClick={() => onRegenerate()}
                      style={{ marginLeft: 10, fontSize: 13, color: t.link, background: "none", border: "none", cursor: "pointer", textDecoration: "underline" }}
                    >
                      try again
                    </button>
                  )}
                </p>
              )}

              <div ref={founderRef} aria-hidden="true" style={{ height: 0 }} />
              <FounderSlot t={t} />

              <BriefFooterActions
                t={t}
                status={status}
                viewingFromSaved={viewingFromSaved}
                isReEvalResult={isReEvalResult}
                saveStatus={saveStatus}
                onSaveIdea={onSaveIdea}
                onNewIdea={onNewIdea}
                goToMyIdeas={goToMyIdeas}
                setCurrentScreen={setCurrentScreen}
                onRegenerate={onRegenerate}
              />
            </>
          )}

          <p style={{ fontSize: 11.5, color: t.mut, textAlign: "center", margin: 0, lineHeight: 1.5 }}>
            IdeaLoop Core — all analysis is AI-generated. Use as a guide, not a definitive assessment.
          </p>
        </PageContainer>
      </main>

      <footer style={footerStyle}>
        <PageContainer wide>
          <p style={{ fontSize: 12, color: t.mut, margin: 0 }}>
            IdeaLoop Core — All analysis is AI-generated. Use as a guide, not a definitive assessment.
          </p>
        </PageContainer>
      </footer>

      {/* Crossing overlay — sharp animation over a blurred backdrop (the brief
          assembles behind it). Mirrors the analyze streaming overlay pattern. */}
      {overlay !== "hidden" && (
        <div
          style={{
            position: "fixed", top: 0, left: 0, right: 0, bottom: 0, zIndex: 9999,
            display: "flex", alignItems: "center", justifyContent: "center",
            backdropFilter: "blur(8px)", WebkitBackdropFilter: "blur(8px)",
            background: t.streamOverlay,
            opacity: overlay === "fading" ? 0 : 1,
            transition: "opacity .4s ease-out",
            animation: overlay === "up" ? "ebOverlayIn .3s ease-out" : "none",
          }}
        >
          <div
            style={{
              background: t.surface,
              border: `1px solid ${t.streamBorder}`,
              borderRadius: 14,
              padding: "36px 28px",
              width: "92%",
              maxWidth: 600,
              boxShadow: t.streamShadow,
              display: "flex",
              justifyContent: "center",
            }}
          >
            <BriefCrossing t={t} status={status} />
          </div>
          <style>{`@keyframes ebBreathe{0%,100%{transform:translate(-50%,-50%) scale(1);opacity:.7}50%{transform:translate(-50%,-50%) scale(1.22);opacity:1}}@keyframes ebOverlayIn{from{opacity:0}to{opacity:1}}`}</style>
        </div>
      )}
    </div>
  );
}